### ISSUE TITLE
[Docker Desktop Extension] - Investigate info error 'failed to get replica' on correctly deployed apps

### ISSUE THREAD

**Issue by mmartin24** [epinio/extension-docker-desktop#6]
**Issue**:
We should investigate why a correctly deployed app using Docker Desktop produces always this error oon the info panel from Docker Desktop / Info panel on epinio

```
failed to get replica details: the server could not find the requested resource (get pods.metrics.k8s.io)
```

![Image](https://user-images.githubusercontent.com/37271841/195084557-630782d3-b38d-4e05-a93b-90c3b736a1a3.png)

Tested on Ubuntu 22.04 with Epinio 1.1.0

**Comment by mmartin24** [comment]
It seems to be ok. See before after::




![Image](https://user-images.githubusercontent.com/37271841/195086414-70df97df-2c6f-46d3-8da7-06fbddbd35a9.png)



![Image](https://user-images.githubusercontent.com/37271841/195086558-71bcefa9-698c-4bd8-b7ce-a3e1eecd53c0.png)

**Comment by thehejik** [comment]
The error message is visible due to missing `metrics-server` running in DD k8s cluster. 

#### How to fix it in the dd cluster:

```
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
```
then edit the deployment by: `kubectl edit deploy metrics-server -n kube-system` command and provide extra arg `--kubelet-insecure-tls` at the end of the list in `.spec.containers.args`.

```
    spec:
      containers:
      - args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
```
![image](https://user-images.githubusercontent.com/12828077/195093418-960f6c8b-7309-46b9-b9ca-e804231f5faf.png)
